modLoader="javafml"
loaderVersion="[40,)"
license="BSD 3-Clause New or Revised License"

[[mods]]
modId="simple_hearts"
version="1.1.4"
displayName="Simple Hearts"
credits="Made with hearts and love."
displayURL="https://github.com/Yr1t/simplehearts"
authors="Yrit"
description='''
A simple Minecraft mod that adds survival friendly ways of getting extra health.
'''

[[dependencies.simple_hearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




