modLoader="javafml"
loaderVersion="[47,)"
license="Ace3 Style BSD"

[[mods]]
modId="simple_hearts"
version="2.0"
displayName="Simple Hearts"
displayURL="https://github.com/Yr1t/simplehearts"
logoFile="logo.png"
credits="Created with love <3"
authors="yrit"
description="A simple, survival friendly extra health mod."

[[dependencies.simple_hearts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.simple_hearts]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

